const THEME_BLUE = "#27a4e1";
const THEME_PRIMARY = "#2b9bdc";
const THEME_SECONDARY = "#26ED95";
const THEME_BG = "#F8F8F8";
const THEME_WHITE = "#FFF";
const THEME_GREY_ONE = "#4D4D4D";
const THEME_GREY_TWO = "#7C7C7C";
const THEME_GREY_THREE = "#8C8C8C";

export default {
  THEME_BLUE,
  THEME_PRIMARY,
  THEME_SECONDARY,
  THEME_GREY_ONE,
  THEME_GREY_TWO,
  THEME_GREY_THREE,
  THEME_BG,
  THEME_WHITE
};
